### ISSUE TITLE
Undefined variable marked on variables xx{{yy}}zz

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#151] opened 2023-05-12 07:47 UTC
![image](https://github.com/equinor/septic-config-generator/assets/44671818/8368a0df-cbfd-4e1d-8401-39adc4798a7b)

**Comment by vetlek** [comment] 2023-05-12 13:41
Unable to recreate bug when using the same variable name as highlighted and with an Evr with the same name. This might be related to a previous release of the extension. Could you check if the same error occurs using version 1.3^ @palkitt ?

**Comment by einarsi** [comment] 2023-05-15 09:06
I think perhaps it's not the Jinja part but perhaps something else that is causing this? I was seeing something similar for another set of templates:

File 21 reports missing L1P:
![image](https://github.com/equinor/vscode-septic/assets/2356425/bdd58632-2fe5-4606-afd8-262c115f8f1d)

But in file 31 it is defined:
![image](https://github.com/equinor/vscode-septic/assets/2356425/add51966-c855-497c-aaa0-4519904fa6f4)

Reordering the files (placing 31 before 21 in the yaml makes the problem go away. So it seems as if the check wrongly assumes that the definition of a variable must come before its use?

**Comment by palkitt** [comment] 2023-05-15 11:45
I'm using v 1.3.0. For the specific case, the XVR is defined in a file coming forther down in the list of files to be included. Is is defined as: LC{{Temp}}RampDn. Does it make difference what the "template" variable is called?

**Comment by vetlek** [comment] 2023-05-16 13:21
> I think perhaps it's not the Jinja part but something else that is causing this: I was seeing something similar for another set of templates:
> 
> File 21 reports missing L1P: ![image](https://user-images.githubusercontent.com/2356425/238295835-bdd58632-2fe5-4606-afd8-262c115f8f1d.png)
> 
> But in file 31 it is defined: ![image](https://user-images.githubusercontent.com/2356425/238296157-add51966-c855-497c-aaa0-4519904fa6f4.png)
> 
> Reordering the files (placing 31 before 21 in the yaml) makes the problem go away. So it seems as if the check wrongly assumes that the definition of a variable must come before it is used?
> 
> Using v1.3.0

In theory this should not matter. All refs are extracted from the relevant files in the context without considering the order of the files (but it is done sequentially).

Not able to reproduce it by simply switching the order of the files in the yaml.

**Comment by einarsi** [comment] 2023-05-31 08:09
Another case where this happens is if the Xvr name starts with a number:
![image](https://github.com/equinor/vscode-septic/assets/2356425/a5c22324-830b-4a68-980e-382648ed6c1b)
Rename all instances to start with e.g. 'x', and it works fine:
![image](https://github.com/equinor/vscode-septic/assets/2356425/13ffd4a9-6d9c-4a05-bb43-d833cdb74bfc)

**Comment by vetlek** [comment] 2023-06-06 13:19
> Another case where this happens is if the Xvr name starts with a number: ![image](https://user-images.githubusercontent.com/2356425/242204391-a5c22324-830b-4a68-980e-382648ed6c1b.png) Rename all instances to start with e.g. 'x', and it works fine: ![image](https://user-images.githubusercontent.com/2356425/242204072-13ffd4a9-6d9c-4a05-bb43-d833cdb74bfc.png)

Bug due to the order of regex used in the parsing of the septic. The SopcTvr name will be PSTxxx since the first part is considered a number, which then leads to warning.

**Comment by vetlek** [comment] 2023-06-06 14:05
Suspect this issue might be related to #177. @einarsi @palkitt : Are the errors from projects where there are multiple applications i.e. several different scg folders with templates?

**Comment by vetlek** [comment] 2023-06-21 06:20
Fixed in release 1.4. Closing.

**Closed by vetlek** 2023-06-21 06:20 UTC
